import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { classify } from "@/lib/glucose";

export interface ReadingExport {
  value: number;
  meal_context: string | null;
  measured_at: string;
  created_at: string;
}

export function exportReadingsPdf(opts: {
  username: string | null;
  readings: ReadingExport[];
}) {
  const doc = new jsPDF();
  const now = new Date();

  doc.setFontSize(18);
  doc.text("GlucoTrack — Glucose Report", 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Patient: ${opts.username ?? "—"}`, 14, 26);
  doc.text(`Generated: ${now.toLocaleString()}`, 14, 31);
  doc.text(`Total readings: ${opts.readings.length}`, 14, 36);

  // Summary
  const values = opts.readings.map((r) => r.value);
  const avg = values.length ? Math.round(values.reduce((a, b) => a + b, 0) / values.length) : 0;
  const min = values.length ? Math.min(...values) : 0;
  const max = values.length ? Math.max(...values) : 0;
  const high = values.filter((v) => v > 140).length;
  const low = values.filter((v) => v < 70).length;

  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.text("Summary", 14, 48);
  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text(`Average: ${avg} mg/dL    Min: ${min}    Max: ${max}`, 14, 55);
  doc.text(`High (>140): ${high}    Low (<70): ${low}`, 14, 60);

  autoTable(doc, {
    startY: 68,
    head: [["Date / Time", "Value (mg/dL)", "Status", "Context"]],
    body: opts.readings.map((r) => [
      new Date(r.measured_at ?? r.created_at).toLocaleString(),
      String(r.value),
      classify(r.value).label,
      (r.meal_context ?? "—").replace("_", " "),
    ]),
    styles: { fontSize: 9 },
    headStyles: { fillColor: [16, 185, 129] },
  });

  doc.setFontSize(8);
  doc.setTextColor(150);
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(
      "Generated by GlucoTrack — for personal records only, not a medical document.",
      14,
      doc.internal.pageSize.getHeight() - 8,
    );
  }

  const file = `glucotrack-report-${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(file);
}
